/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.restaurantSystem.view;

/**
 *
 * @author user
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        mnuMenu = new javax.swing.JMenu();
        mnuEvent = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        mnuGestion = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        mnuAccount = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jMenu1.setText("Lo Nuestro R&E");
        jMenu1.setToolTipText("");

        jMenuItem5.setText("Acerca de..");
        jMenu1.add(jMenuItem5);

        jMenuItem13.setText("Salir");
        jMenu1.add(jMenuItem13);

        jMenuBar1.add(jMenu1);

        mnuMenu.setText("Menu");
        mnuMenu.setToolTipText("Mostrar menu");
        mnuMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuMenu);

        mnuEvent.setText("Eventos");
        mnuEvent.setToolTipText("Mostrar eventos");

        jMenuItem6.setText("Agenda");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem6MouseClicked(evt);
            }
        });
        mnuEvent.add(jMenuItem6);

        jMenuItem7.setText("Nuevo Evento");
        jMenuItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem7MouseClicked(evt);
            }
        });
        mnuEvent.add(jMenuItem7);

        jMenuBar1.add(mnuEvent);

        mnuOrder.setText("Ordenes");
        mnuOrder.setToolTipText("Mostrar ordenes");
        mnuOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOrderMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuOrder);

        mnuGestion.setText("Gestión");
        mnuGestion.setToolTipText("Mostrar gestion");

        jMenuItem8.setText("Menú");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnuGestion.add(jMenuItem8);

        jMenuItem10.setText("Servicios para Eventos");
        mnuGestion.add(jMenuItem10);

        jMenuBar1.add(mnuGestion);

        mnuReport.setText("Reportes");
        mnuReport.setToolTipText("Mostrar reportes");

        jMenuItem11.setText("Ordenes");
        mnuReport.add(jMenuItem11);

        jMenuItem12.setText("Eventos");
        mnuReport.add(jMenuItem12);

        jMenuBar1.add(mnuReport);

        mnuAccount.setText("Cuentas");
        mnuAccount.setToolTipText("Mostrar cuentas");
        mnuAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAccountMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuAccount);

        jMenu8.setText("Ayuda");
        jMenu8.setToolTipText("Ayuda");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAccountMouseClicked
        // TODO add your handling code here:
        FrmNewAccount account = new FrmNewAccount();
        account.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuAccountMouseClicked

    private void mnuMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMenuMouseClicked
        // TODO add your handling code here:
        FrmMenuOption menuOp = new FrmMenuOption();
        menuOp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuMenuMouseClicked

    private void jMenuItem7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem7MouseClicked
        // TODO add your handling code here:
        FrmEvent frmE = new FrmEvent();
        frmE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7MouseClicked

    private void jMenuItem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MouseClicked
        // TODO add your handling code here:
        FrmScheduleEvent schedule = new FrmScheduleEvent();
        schedule.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6MouseClicked

    private void mnuOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOrderMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mnuOrderMouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        FrmDish dish = new FrmDish();
        dish.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu mnuAccount;
    private javax.swing.JMenu mnuEvent;
    private javax.swing.JMenu mnuGestion;
    private javax.swing.JMenu mnuMenu;
    private javax.swing.JMenu mnuOrder;
    private javax.swing.JMenu mnuReport;
    // End of variables declaration//GEN-END:variables
}
